{"uuid": "979964af-1176-427f-9679-cecaf4627ffc", "children": ["d0939475-0ca8-496e-a158-8d7abd4d20d3"], "befores": [{"name": "user_login_valid_creds", "status": "passed", "steps": [{"name": "Получить ответ на запрос регистрации нового пользователя", "status": "passed", "steps": [{"name": "Сформировать тело запроса для регистрации курьера", "status": "passed", "start": 1715354383060, "stop": 1715354383060}], "start": 1715354383060, "stop": 1715354383591}], "start": 1715354383060, "stop": 1715354383591}], "afters": [{"name": "user_login_valid_creds::0", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))\n", "trace": "  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\conftest.py\", line 52, in user_login_valid_creds\n    shared_methods.delete_user(token)\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\helper_functions\\shared_methods.py\", line 55, in delete_user\n    return requests.delete(\n           ^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\api.py\", line 157, in delete\n    return request(\"delete\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 501, in send\n    raise ConnectionError(err, request=request)\n"}, "steps": [{"name": "Логин пользователя с данными {'email': 'nm8oy0e049@yandex.ru', 'password': 'xop1y16x', 'name': 'z9h42'}", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'nm8oy0e049@yandex.ru', 'password': 'xop1y16x', 'name': 'z9h42'}"}], "start": 1715354402144, "stop": 1715354412286}, {"name": "Удалить юзера", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))\n", "trace": "  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\helper_functions\\shared_methods.py\", line 55, in delete_user\n    return requests.delete(\n           ^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\api.py\", line 157, in delete\n    return request(\"delete\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\projects\\py\\yandex\\diplom\\Diplom_3\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 501, in send\n    raise ConnectionError(err, request=request)\n"}, "parameters": [{"name": "token", "value": "'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2UzYjBmOWVkMjgwMDAxYjQwOGQ2YyIsImlhdCI6MTcxNTM1NDQwOSwiZXhwIjoxNzE1MzU1NjA5fQ.YYlzjx0e_Zse2W2gvGWet3mYADT45dM7xDB5E0rejRM'"}], "start": 1715354412286, "stop": 1715354423250}], "start": 1715354402144, "stop": 1715354423265}], "start": 1715354383060, "stop": 1715354423265}